DROP TABLE IF EXISTS task;

CREATE TABLE IF NOT EXISTS task
(
    id         SERIAL PRIMARY KEY,
    owner_id   BIGINT UNSIGNED,
    title      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (owner_id) REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
