DROP TABLE IF EXISTS task;

CREATE TABLE IF NOT EXISTS task
(
    id         SERIAL PRIMARY KEY,
    user_id    BIGINT UNSIGNED,
    token      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
